testing

diff --git a/.github/workflows/github-action.yml b/.github/workflows/github-action.yml
--- a/.github/workflows/github-action.yml
+++ b/.github/workflows/github-action.yml
@@ -1,17 +1,7 @@
 name: GitHub Actions Demo	
 on: [push]
 jobs:
-  Build:
-   runs-on: ubuntu-latest
-   needs: [Lint]
-   steps:
-    - name: Test
-      run: echo "Hello world"
-    - name: Check out repository code
-      uses: actions/checkout@v4
-    - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
-    - run: ls
-    - run: go build k8-sample.go
+  
   
   Lint:
     runs-on: ubuntu-latest
@@ -39,5 +29,26 @@ jobs:
          uses: actions/checkout@v4
        - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
        - run: ls
-       - run: go test .
+       - run: go test . -cover
+       - name: Run tests and check coverage
+         run: |
+            go test -coverprofile=coverage.out ./...
+            go tool cover -func=coverage.out | grep total: | awk '{print $3}' | sed 's/%//' > coverage.txt
+            coverage=$(cat coverage.txt)
+            echo "Code coverage is $coverage%"
+            if (( $(echo "$coverage < 90" | bc -l) )); then
+              echo "Coverage is below 90%. Failing build."
+              exit 1
+            fi
+  Build:
+              runs-on: ubuntu-latest
+              needs: [Lint]
+              steps:
+               - name: Test
+                 run: echo "Hello world"
+               - name: Check out repository code
+                 uses: actions/checkout@v4
+               - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
+               - run: ls
+               - run: go build k8-sample.go
 
